import pandas as pd
from src.data.load_data import load_final_data

MODEL_FEATURES = [
    "architecture",
    "process_size_nm",
    "transistors_million",
    "density_M__per__mm^2",
    "die_size_mm²",
    "base_clock_MHz",
    "memory_size_GB",
    "memory_type",
    "memory_bus_bit",
    "bandwidth_GBs",
    "shading_units",
    "tmus",
    "rops",
    "l1_cache_KB_per_CU",
    "l2_cache_MB",
    "directx",
    "tdp_W",
    "memory_clock_MHz",
    "fp32_TFLOPS",
    "fp64_TFLOPS",
    "pixel_rate_GPixel/s",
    "texture_rate_GTexel/s",
    "Game_Name",
    "Avg_FPS",
    "Setting",
    "Resolution",
    "launch_price_USD"
]


def get_gpu_specs(gpu_name, df):
    """
    Retrieve GPU specifications by name.
    """
    try:
        return df.loc[gpu_name].iloc[0].to_dict()
    except KeyError:
        raise ValueError(f"GPU not found: {gpu_name}")


def get_observed_fps(gpu_name, game, resolution, benchmark_df):
    row = benchmark_df[
        (benchmark_df.index.str.lower() == gpu_name.lower()) &
        (benchmark_df["Game_Name"].str.lower() == game.lower()) &
        (benchmark_df["Resolution"].str.lower() == resolution.lower())
    ]
    if row.empty:
        return None
    return float(row.iloc[0]["Avg_FPS"])


def prepare_features(user_input, df):
    gpu_specs = get_gpu_specs(user_input["gpu_name"], df)
    features = {feature: gpu_specs[feature] for feature in MODEL_FEATURES}
    return features


def predict_fps_from_features(features, model):
    df = pd.DataFrame([features], columns=MODEL_FEATURES)
    pred = model.predict(df)[0]
    return max(0.0, int(pred))


def answer_fps_query(user_input, model):
    """
    Return the FPS for a given GPU, game, and resolution.

    The function first checks whether an observed benchmark value exists
    in the benchmark dataset. If an exact match is found, the observed
    FPS is returned. If no benchmark exists, the function constructs a
    feature vector using the GPU specifications and uses the trained
    XGBoost model to generate a predicted FPS value.

    Parameters
    ----------
    user_input : dict
        Dictionary containing query parameters such as:
        {
            "gpu_name": str,
            "game": str,
            "resolution": str
        }

    gpu_df : pandas.DataFrame
        DataFrame containing GPU hardware specifications used to build
        the model feature vector.

    benchmark_df : pandas.DataFrame
        DataFrame containing observed benchmark FPS values for GPU,
        game, and resolution combinations.

    model : object
        Trained regression model (e.g., XGBoost) used to predict FPS
        when an observed benchmark is not available.

    Returns
    -------
    dict
        Dictionary containing:
        {
            "fps": float,
            "source": str
        }

        source will be:
        - "observed" if the FPS comes from the benchmark dataset
        - "predicted" if the FPS was generated by the model
    """
    df = load_final_data()
    observed = get_observed_fps(
        user_input["gpu_name"],
        user_input["game"],
        user_input["resolution"],
        df
    )
    if observed is not None:
        return {
            "fps": observed,
            "source": "observed"
        }

    features = prepare_features(user_input, df)
    predicted = predict_fps_from_features(features, model)

    return {
        "fps": predicted,
        "source": "predicted"
    }
